Added forward url's and local url's
3Dpass/wallet pull request #10
Opened 2023-03-18 18:34 UTC by WlinkNET

Just check pnpm-lock.yaml didnt change after rebase

2023-03-18 23:55 UTC, fedosov requested changes

2023-03-18 23:55 UTC, fedosov commented on app/components/block/Block.client.tsx
> +    setIsFinalized(block.block.header.number.toNumber() <= bestNumberFinalized);
Let's extract the block number into a const. It is used multiple times.

2023-03-18 23:55 UTC, fedosov commented on app/components/common/ExplorerForward.tsx
> +const BASE_URL = "https://explorer.3dpass.org";
Do you think we should move this to our config where an API URL already exists?

2023-03-18 23:55 UTC, fedosov commented on pnpm-lock.yaml
No need to prettify this file. It is generated automatically. Please revert to the previous state.

2023-03-18 23:59 UTC, WlinkNET commented on app/components/common/ExplorerForward.tsx
> +const BASE_URL = "https://explorer.3dpass.org";
We can but I will leave it here bcs will build all stuff if forward explorer on one place.

2023-03-18 23:59 UTC, WlinkNET commented on app/components/block/Block.client.tsx
> +    setIsFinalized(block.block.header.number.toNumber() <= bestNumberFinalized);
Sure I saw that and also want to ask you that,

2023-03-19 00:00 UTC, WlinkNET commented on pnpm-lock.yaml
Its not prettify it was corrupted when I rebase it

2023-03-19 00:01 UTC, fedosov commented on pnpm-lock.yaml
Okay, please take the current file from main branch so there is not diff

2023-03-19 00:10 UTC, WlinkNET commented on pnpm-lock.yaml
ok

2023-03-19 00:14 UTC, WlinkNET commented on app/components/block/Block.client.tsx
> +    setIsFinalized(block.block.header.number.toNumber() <= bestNumberFinalized);
I added const blockNumber = block.block.header.number.toString();

2023-03-19 00:19 UTC, merged