Sign and Verify dialog
3Dpass/wallet pull request #15
Opened 2023-03-23 13:03 UTC by WlinkNET

2023-03-23 14:55 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +    setIsDialogOpen(true);
Why wouldn't you use `dialogToggle`?

2023-03-23 14:55 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +  const [messageType, setMessageType] = useState("sign");
Let's use constants for the states as it is easy to do a mistype somewhere

2023-03-23 14:56 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +      if (pair.meta.isInjected) {
Create utility `getSigner` as we did with `signAndSend` (also use it there). This will simplify code

2023-03-23 14:58 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +      setFormattedMessage &&
What do you check with this condition?

2023-03-23 14:59 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +  const textareaRef = useRef();
Where do you use this? Can't find any examples by searching

2023-03-23 15:00 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +                  style={{
Please use TailwindCSS classes instead of raw styles. Eg.: `height-[220px] width-full padding-3 text-start`

2023-03-23 15:01 UTC, fedosov commented on styles/app.css
> +.footer-actions {
Please use TailwindCSS classes in HTML code, do not put styling here.

2023-03-23 16:51 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +      setFormattedMessage &&
This one is for copy whole message after sign

2023-03-23 16:52 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +  const textareaRef = useRef();
Missed to delete when do cleanup

2023-03-23 16:57 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +  const [messageType, setMessageType] = useState("sign");
ok

2023-03-23 18:01 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +      setFormattedMessage &&
But what is the purpose of checking the setFormattedMessage? It is always true

2023-03-23 18:12 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +      setFormattedMessage &&
Ok I can write it like this then
```
const handleCopyClick = () => {
  const messageToCopy =
    `-- Start message --\n ${message}\n-- End message --\n\n-- Start P3D wallet signature --\n${signedMessage}\n-- End P3D wallet signature --\n\n-- Start public key --\n${publicKey}\n-- End public key --`;

  navigator.clipboard.writeText(messageToCopy).then(() => {
    toaster.show({
      message: "Message copied to clipboard!",
      intent: Intent.SUCCESS,
      icon: "tick",
    });
  });
};

```

2023-03-23 21:45 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +          <div className="grid grid-cols-3 gap-1">
Is this necessary to have a grid here just for one button?

2023-03-23 21:49 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +    if (messageType === "verify") {
You can't call this from `sign`, so remove redundant condition

2023-03-23 21:49 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +        console.error("Failed to paste content: ", err);
Should we let user know what happened, not only developers

2023-03-23 21:51 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +      if (messageType === "verify") {
This seems not necessary

2023-03-24 17:35 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +        if (isSigned.isValid) {
Why not just `setIsSignatureValid(isSigned.isValid);`?!

2023-03-24 17:36 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +                    setFormattedMessage &&
What it is meant to check with `setFormattedMessage`?!

2023-03-24 17:37 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +                <div className="flex justify-between items-center footer-actions">
Can you cleanup unused classes? (eg. `footer-actions`)
Let's keep codebase clean

2023-03-24 17:39 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +                    {isSignatureValid === true && messageType === "verify" ? (
Checking for `messageType === "verify"` doesn't make sense here. Doesn't we already know that it is always `verify` here?

2023-03-24 17:39 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +  const [messageType, setMessageType] = useState("sign");
So, what do you think?

2023-03-24 19:43 UTC, fedosov commented on app/routes/network.tsx
> +  const accounts = await api.query.system.account.entries();
This should be in a separate PR because this is a different task.

2023-03-24 23:18 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +  const [messageType, setMessageType] = useState("sign");
Do we replace this?

2023-03-25 01:24 UTC, WlinkNET commented on app/components/wallet/Account.client.tsx
> +    setIsDialogOpen(true);
Fixed

2023-03-25 01:25 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +      setFormattedMessage &&
This ok?

2023-03-25 01:25 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +                  style={{
Fixed

2023-03-25 01:25 UTC, WlinkNET commented on styles/app.css
> +.footer-actions {
Fixed

2023-03-25 01:26 UTC, WlinkNET commented on app/components/wallet/Account.client.tsx
> +          <div className="grid grid-cols-3 gap-1">
We leave this as agreed

2023-03-25 01:26 UTC, WlinkNET commented on app/components/wallet/Account.client.tsx
> +    dialogToggle("sign_verify");
Fixed

2023-03-25 01:27 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +    if (messageType === "verify") {
Fixed

2023-03-25 01:27 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +        console.error("Failed to paste content: ", err);
Fixed

2023-03-25 01:28 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +          console.error("Unable to extract message and signature from pasted data");
Deleted

2023-03-25 01:28 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +      if (messageType === "verify") {
Fixed

2023-03-25 01:31 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +        if (isSigned.isValid) {
Fixed

2023-03-25 01:31 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +                    setFormattedMessage &&
Fixed

2023-03-25 01:31 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +                <div className="flex justify-between items-center footer-actions">
Fixed

2023-03-25 01:32 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +                    {isSignatureValid === true && messageType === "verify" ? (
Fixed

2023-03-25 13:54 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +    <>
You don't need this extra empty tag here `<>`

2023-03-25 14:00 UTC, fedosov requested changes

2023-03-25 14:00 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +        setshowValidationResults(true);
You also need to reset this to `false` when a user changes the contents of the textarea or address. Because it would not be valid statement at the moment of change.

2023-03-25 14:04 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +                  value={`-- Start message --\n ${message}\n-- End message --\n\n-- Start P3D wallet signature --\n${signedMessage}\n-- End P3D wallet signature --\n\n-- Start public key --\n${public
Please use constant for this

2023-03-25 14:21 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +    <>
I tried to delete it but it breaks I dont get it why. If you know why please provide me

2023-03-25 15:15 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +    <>
Any clues? Error message? You can bring the developer console in the Chrome browser by Option + ⌘ + J (on macOS), or Shift + CTRL + J (on Windows/Linux)

2023-03-25 15:16 UTC, fedosov commented on app/components/dialogs/DialogSignVerify.tsx
> +                <div className="flex justify-between items-center footer-actions">
I mean all the classes. `footer-actions`was an example.

2023-03-25 19:24 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +    <>
fixed

2023-03-25 19:24 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +                        <Icon className="verified-icon" icon="endorsed" intent={Intent.SUCCESS} />
removed

2023-03-25 19:25 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +  function handleOnOpening() {
fixed

2023-03-25 19:25 UTC, WlinkNET commented on app/components/dialogs/DialogSignVerify.tsx
> +                  value={`-- Start message --\n ${message}\n-- End message --\n\n-- Start P3D wallet signature --\n${signedMessage}\n-- End P3D wallet signature --\n\n-- Start public key --\n${public
fixed

2023-03-25 19:33 UTC, fedosov approved these changes

2023-03-25 19:37 UTC, merged