Mining pool control panel
3Dpass/wallet pull request #17
Opened 2023-04-11 20:35 UTC by evgeniikozhanov

2023-04-11 20:42 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +  const [apiAdvancedMode] = useAtom(apiAdvancedModeAtom);
Когда надо только читать значение, то есть такой вот хук: useAtomValue

2023-04-11 20:43 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +            {apiAdvancedMode && (
В проекте есть prettier, я так понимаю он не настроен у тебя пока что. Посмотри плагин для своей IDE. Это автоматическое форматирование кода.

2023-04-12 13:38 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +            {apiAdvancedMode && (
done

2023-04-12 13:39 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +  const [apiAdvancedMode] = useAtom(apiAdvancedModeAtom);
thanks, I changed

2023-04-17 15:25 UTC, fedosov requested changes

2023-04-17 15:25 UTC, fedosov commented on app/components/common/Select.tsx
> +    console.log(options);
Отладочное логирование надо убрать

2023-04-17 15:25 UTC, fedosov commented on app/components/common/Select.tsx
> +    <select value={toValue(value)} onChange={handleChange}>
Давай какой-нибудь компонент из BP возьмем? Там и поиск есть по списку

https://blueprintjs.com/docs/#select/suggest2 вот, например

А этот компонент может быть не нужен тогда и его можно удалить?

2023-04-17 15:25 UTC, fedosov commented on app/components/dialogs/DialogSettings.tsx
> +    api_advanced_sign: apiAdvancedMode,
Давай это консистенто назовем `api_advanced_mode`, как и другие переменные

2023-04-17 15:25 UTC, fedosov commented on app/components/dialogs/DialogSettings.tsx
> +            Advanced
Advanced mode

2023-04-17 15:25 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +      <DialogSetPoolInterest isOpen={dialogs.set_pool_interest} onClose={() => onCloseTransactionDialog("set_pool_interest")} pair={pair} />
Вот эти кнопки по идее не должны быть доступны, если пул еще не создан. Можем это как-то отследить? Причем именно что пул создан на самом деле, а не просто нажали кнопку создания пула. Надо дождаться что он создался.
Кнопку создания пула тоже по идее надо дизейблить когда пул создан.

2023-04-17 15:25 UTC, fedosov commented on app/components/common/InterestInput.tsx
> +      clampValueOnBlur={true}
Смотри, тут мало разницы по сравнению с `AmountInput`. Давай этот компонент удалим, а в `AmountInput` добавим возможность выводить вместо знака валюты знак процента, например. Иначе получается усложняющее дублирование кода.

2023-04-17 15:25 UTC, fedosov commented on app/components/dialogs/DialogCreatePool.tsx
> +  }, [api, {}]);
Для чего тут нужен `{}`?

2023-04-17 15:25 UTC, fedosov commented on package.json
> +}
Это признак, что возможно у тебя не подцепились настройки editorconfig, проверь

2023-04-17 15:25 UTC, fedosov commented on app/utils/pool.ts
> +export const filterPool = (poolBox: IPoolBox, accountId: string): IPoolBox => {
Давай попробуем методы называть проще и очевиднее, чтобы комменты к ним даже не нужны были. Что думаешь на счет `poolsWithMember`?

2023-04-17 18:55 UTC, evgeniikozhanov commented on .prettierrc
> +{
ah, I merged several days ago, so I can just merge it today, sorry. Done.

2023-04-17 18:55 UTC, evgeniikozhanov commented on app/components/dialogs/DialogSettings.tsx
> +    api_advanced_sign: apiAdvancedMode,
ok

2023-04-17 18:55 UTC, evgeniikozhanov commented on app/components/dialogs/DialogSettings.tsx
> +            Advanced
ok

2023-04-17 18:56 UTC, evgeniikozhanov commented on app/components/dialogs/DialogJoinPool.tsx
> +    loadPools().then(() => {});
ok

2023-04-17 18:56 UTC, evgeniikozhanov commented on package.json
> +}
VsCode has a separate setting for last lines :smile:

2023-04-17 18:58 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +  function updateBalances() {
yes, I figured this out after my last doings with pools. I removed this function.

2023-04-17 19:01 UTC, evgeniikozhanov commented on app/utils/pool.ts
> +export const filterPool = (poolBox: IPoolBox, accountId: string): IPoolBox => {
yes, good idea, I changed, thanks

2023-04-17 19:13 UTC, evgeniikozhanov commented on app/components/common/InterestInput.tsx
> +      clampValueOnBlur={true}
ok. done.

2023-04-17 19:13 UTC, evgeniikozhanov commented on app/components/dialogs/DialogCreatePool.tsx
> +  }, [api, {}]);
I have no idea. I removed it.

2023-04-17 20:21 UTC, evgeniikozhanov commented on app/components/common/Select.tsx
> +    console.log(options);
It's not actual anymore, the file was deleted.

2023-04-17 20:37 UTC, fedosov commented on app/components/common/Select.tsx
> +    <select value={toValue(value)} onChange={handleChange}>
You can commit select2, I will check how to change it's width

2023-04-18 18:54 UTC, fedosov requested changes

2023-04-18 18:54 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +                  <Button text="Create a pool" onClick={() => dialogToggle("create_pool")} disabled={pair.isLocked && !pair.meta.isInjected} />
Сейчас получится сделать чтобы кнопки работали в зависимости от того создан уже пел или нет? Не давать создать если уже создать и не давать поменять параметры если пула еще нет.

2023-04-18 18:54 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +                  <Button text="Join a pool" onClick={() => dialogToggle("join_pool")} disabled={pair.isLocked && !pair.meta.isInjected} />
Давай тут сразу везде `pair.isLocked && !pair.meta.isInjected` заодно заменим на константу. Что-то типа `accountLocked`

2023-04-18 21:16 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +                  <Button text="Join a pool" onClick={() => dialogToggle("join_pool")} disabled={pair.isLocked && !pair.meta.isInjected} />
ok. done.

2023-04-20 11:43 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +      <DialogSetPoolInterest isOpen={dialogs.set_pool_interest} onClose={() => onCloseTransactionDialog("set_pool_interest")} pair={pair} />
it seems I did it

2023-04-20 11:43 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +                  <Button text="Create a pool" onClick={() => dialogToggle("create_pool")} disabled={pair.isLocked && !pair.meta.isInjected} />
it seems I did it

2023-04-20 14:36 UTC, fedosov commented on app/utils/sign.ts
> +export async function signAndSendWithSubscribtion(
Давай объединим в одну функцию. Они почти идентичные с `signAndSend`.

2023-04-20 16:20 UTC, evgeniikozhanov commented on app/components/dialogs/DialogCreatePool.tsx
> +        if (status.isFinalized) {
ok, fixed.

2023-04-20 16:22 UTC, evgeniikozhanov commented on app/utils/sign.ts
> +export async function signAndSendWithSubscribtion(
I tried, but I can't call `unsub()` in that case, because the function result has another return type.

2023-04-20 16:34 UTC, fedosov approved these changes

2023-04-22 20:15 UTC, merged