Feature/identity UI
3Dpass/wallet pull request #24
Opened 2023-04-23 20:39 UTC by evgeniikozhanov

2023-04-23 20:49 UTC, fedosov requested changes

2023-04-23 20:49 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +        className="bp4-icon bp4-intent-success"
Константы

2023-04-23 20:49 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +        style={{'position': 'absolute', 'right': '0.3rem', 'top': '2.5rem', 'cursor': 'pointer'}}
Юзай tailwind

2023-04-23 20:49 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +            <Select2<IPalletIdentityRegistrarInfo>
Странно выглядит, тут нет ошибки?

2023-04-23 20:49 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +    console.log('registrarAccount: ', registrarAccount);
Логирование

2023-04-23 20:49 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +    //   const tx = api.tx.miningPool.addMemberSelf(data.poolToJoin);
Мертвый код

2023-04-23 20:49 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +  }, [api, {}]);
Что значит {}?

2023-04-23 20:49 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +    // image: Any;
Мертвый код

2023-04-23 20:53 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +    console.log('registrarAccount: ', registrarAccount);
wait, wait, it is only a draft)

2023-04-24 11:15 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +            <Select2<IPalletIdentityRegistrarInfo>
it is not necessary, I removed it

2023-04-24 11:15 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +    console.log('registrarAccount: ', registrarAccount);
this block was removed

2023-04-24 11:16 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +    //   const tx = api.tx.miningPool.addMemberSelf(data.poolToJoin);
I started using it now)

2023-04-24 11:16 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +    // image: Any;
I started using it now)

2023-04-24 11:16 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +    // image: Any;
I have no example for it, therefore I have no idea how to deal with it

2023-04-24 11:21 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +        className="bp4-icon bp4-intent-success"
fixed

2023-04-24 17:49 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +        style={{'position': 'absolute', 'right': '0.3rem', 'top': '2.5rem', 'cursor': 'pointer'}}
ok, thanks

2023-04-24 17:50 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +    // image: Any;
my suggestion is that it is base64 data... or url...

2023-05-08 21:58 UTC, fedosov requested changes
Сейчас все адреса помечаются как прошедшие верификацию. Так не должно быть.

2023-05-08 21:58 UTC, fedosov commented on app/components/common/CandidateCards.tsx
> +  dateMonthAgo: Date;
Не понятно зачем сюда передавать это значение, надо подписать

2023-05-08 21:58 UTC, fedosov commented on app/components/common/CandidateCards.tsx
> +                disabled={false}
Это зачем?

2023-05-08 21:58 UTC, fedosov commented on app/components/common/UserCard.tsx
> +          {!registrarInfo.info?.image?.Raw && <Icon icon="person" iconSize={IconSize.LARGE * 3} title="no foto"></Icon>}
Сложно выглядит, можно тут использовать тернарный оператор? `registrarInfo.info?.image?.Raw ? ... : ...`

2023-05-08 21:58 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +    dateMonthAgo: new Date(),
Тоже непонятно. Что это за дата «месяц назад» и почему она равна текущей дате?

2023-05-08 21:58 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +                  disabled={isLoading || !canSubmit}
`canSubmit` всего в одном месте используется и сравнивает api с undefined, давай это упростим

2023-05-08 21:58 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +        {!dataState.isRegistrar && Boolean(pair.meta.isInjected) && <div>You already have identity</div>}
Тут странное условие — если я не регистратор, то у меня уже есть Identity. Это не так, Identity мы должны еще запросить у Registrar, а он его должен одобрить, только тогда у нас появится Identity

2023-05-08 21:58 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +        className={`${Classes.ICON} ${Classes.INTENT_SUCCESS} absolute cursor-pointer right-1 top-9`}
Давай сделаем хотя бы серой иконку, если нет identity, иначе она бесполезная — всегда показывает что у нас есть identity

2023-05-08 21:58 UTC, fedosov commented on app/utils/events.ts
> +  if (queryEvents.data !== undefined && registrarIndex !== undefined && api) {
Давай в таких случаях инвертировать условие и делать return. Так уменьшится идентация у метода

2023-05-08 21:58 UTC, fedosov commented on app/utils/events.ts
> +    for (let i = 0; i < queryEvents.data.getEvents.objects.length; i++) {
`for (const item of queryEvents.data.getEvents.objects) {`

2023-05-09 08:17 UTC, evgeniikozhanov commented on app/components/wallet/Account.client.tsx
> +        className={`${Classes.ICON} ${Classes.INTENT_SUCCESS} absolute cursor-pointer right-1 top-9`}
done

2023-05-09 08:20 UTC, evgeniikozhanov commented on app/components/common/CandidateCards.tsx
> +  dateMonthAgo: Date;
I added a comment for this row

2023-05-09 08:21 UTC, evgeniikozhanov commented on app/components/common/CandidateCards.tsx
> +                disabled={false}
no ideas, removed

2023-05-09 08:21 UTC, evgeniikozhanov commented on app/components/common/UserCard.tsx
> +          {!registrarInfo.info?.image?.Raw && <Icon icon="person" iconSize={IconSize.LARGE * 3} title="no foto"></Icon>}
yes, thank you for your suggestion! done

2023-05-09 08:22 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +    dateMonthAgo: new Date(),
I changed it, hope it becomes more clear

2023-05-09 08:22 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +                  disabled={isLoading || !canSubmit}
ok, I changed it, thanks

2023-05-09 08:23 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +        {!dataState.isRegistrar && Boolean(pair.meta.isInjected) && <div>You already have identity</div>}
The condition is: if I'm not a registrar AND I have an identity. But I'm using a new variable for this purpose, hope it's clear now.

2023-05-09 08:24 UTC, evgeniikozhanov commented on app/utils/events.ts
> +  if (queryEvents.data !== undefined && registrarIndex !== undefined && api) {
I like it! thanks!

2023-05-09 08:24 UTC, evgeniikozhanov commented on app/utils/events.ts
> +    for (let i = 0; i < queryEvents.data.getEvents.objects.length; i++) {
thanks, I adjusted the code

2023-05-09 14:06 UTC, fedosov requested changes
При запросе judgement получаю сообщение «Account is locked», хотя это аккаунт из расширения браузера (т.е. injected), такого не должно быть сообщения

2023-05-09 14:06 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +        text={registrar.fee}
Здесь нужно отформатировать fee, можно использовать компонент `FormattedAmount`

2023-05-09 18:39 UTC, evgeniikozhanov commented
> При запросе judgement получаю сообщение «Account is locked», хотя это аккаунт из расширения браузера (т.е. injected), такого не должно быть сообщения

should be fixed, could you please check it again?

2023-05-09 19:04 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +        label={registrar.account}
but `api.query.identity.registrars()` returns only addresses and fees... Should I call the `getIdentity()` method for each of registrars?

2023-05-09 19:39 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +        label={registrar.account}
Да, стоит попробовать запросить. По идее регистраторов всегда будет ограниченное количество. Если запросы послать параллельно, должно очень быстро отрабатывать

2023-05-09 20:07 UTC, fedosov commented
Попробовал запросить judgement, получил вот такую ошибку:

```
createType(Call):: Call: failed decoding identity.setIdentity:: Struct: failed on args: {"info":"{\"additional\":\"Vec<(Data,Data)>\",\"display\":\"Data\",\"legal\":\"Data\",\"web\":\"Data\",\"riot\":\"Data\",\"email\":\"Data\",\"pgpFingerprint\":\"Option<[u8;20]>\",\"image\":\"Data\",\"twitter\":\"Data\"}"}:: Struct: failed on info: {"additional":"Vec<(Data,Data)>","display":"Data","legal":"Data","web":"Data","riot":"Data","email":"Data","pgpFingerprint":"Option<[u8;20]>","image":"Data","twitter":"Data"}:: Struct: failed on display: {"_enum":{"None":"Null","Raw":"Bytes","BlakeTwo256":"H256","Sha256":"H256","Keccak256":"H256","ShaThree256":"H256"}}:: Unable to decode Data, invalid indicator byte 116
```

Выбирал второго регистратора (Caldera), заполнял поля display name "test identity" и поле discord "fedosov#0974"

@evgeniikozhanov

2023-05-10 21:27 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +        label={registrar.account}
done

2023-05-11 10:38 UTC, evgeniikozhanov commented
> Попробовал запросить judgement, получил вот такую ошибку:
> 
> ```
> createType(Call):: Call: failed decoding identity.setIdentity:: Struct: failed on args: {"info":"{\"additional\":\"Vec<(Data,Data)>\",\"display\":\"Data\",\"legal\":\"Data\",\"web\":\"Data\",\"riot\":\"Data\",\"email\":\"Data\",\"pgpFingerprint\":\"Option<[u8;20]>\",\"image\":\"Data\",\"twitter\":\"Data\"}"}:: Struct: failed on info: {"additional":"Vec<(Data,Data)>","display":"Data","legal":"Data","web":"Data","riot":"Data","email":"Data","pgpFingerprint":"Option<[u8;20]>","image":"Data","twitter":"Data"}:: Struct: failed on display: {"_enum":{"None":"Null","Raw":"Bytes","BlakeTwo256":"H256","Sha256":"H256","Keccak256":"H256","ShaThree256":"H256"}}:: Unable to decode Data, invalid indicator byte 116
> ```
> 
> Выбирал второго регистратора (Caldera), заполнял поля display name "test identity" и поле discord "fedosov#0974"
> 
> @evgeniikozhanov

I reformatted the request structure.

2023-05-11 15:43 UTC, fedosov commented
Не передалось значение из поля Discord. Как тестировал:
завел новый аккаунт
запросил идентити
заполнял поля display name "test identity" и поле discord "fedosov#0974"
у этого аккаунта не заполнено поле discord, только name записался

Проверять поля можно тут: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc2.3dpass.org#/accounts
Нажать на аккаунт и справа будет поле Identity. Там же и должно быть поле DISCORD, если было указано при создании заявки

2023-05-11 21:43 UTC, evgeniikozhanov commented
> Не передалось значение из поля Discord. Как тестировал: завел новый аккаунт запросил идентити заполнял поля display name "test identity" и поле discord "fedosov#0974" у этого аккаунта не заполнено поле discord, только name записался
> 
> Проверять поля можно тут: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc2.3dpass.org#/accounts Нажать на аккаунт и справа будет поле Identity. Там же и должно быть поле DISCORD, если было указано при создании заявки

should be fixed

2023-05-11 21:50 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +        if (key == 'discord') {
Похоже что у тебя форматирование слетело, вроде настраивали ранее

2023-05-11 21:59 UTC, fedosov commented
Дискорд прописался, но другая проблема осталась.

![image](https://github.com/3Dpass/wallet/assets/556770/acc43e68-b757-45b1-a3a6-78ebb905f611)

Мне пишут что requestJudgement экстринсик не отправился в сеть. Он отправляется вообще?

UPD: спустя пару минут у меня появилось окно про эту отправку. Это совсем неинтуитивно. Надо давать пользователю знать что происходит. Я в курсе процесса и все равно я запутался. Должен быть хотя бы какой-то индикатор, что процесс идет и надо ждать, не уходить из кошелька.

2023-05-12 20:55 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +        if (key == 'discord') {
+

2023-05-12 20:57 UTC, evgeniikozhanov commented
> Дискорд прописался, но другая проблема осталась.
> 
> ![image](https://user-images.githubusercontent.com/556770/237821938-acc43e68-b757-45b1-a3a6-78ebb905f611.png)
> 
> Мне пишут что requestJudgement экстринсик не отправился в сеть. Он отправляется вообще?
> 
> UPD: спустя пару минут у меня появилось окно про эту отправку. Это совсем неинтуитивно. Надо давать пользователю знать что происходит. Я в курсе процесса и все равно я запутался. Должен быть хотя бы какой-то индикатор, что процесс идет и надо ждать, не уходить из кошелька.

I added a logic that we show a "success" message only if the second request status is "ready". And I added a warning message for the first request.

2023-05-12 22:11 UTC, fedosov requested changes

2023-05-12 22:11 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +        timeout: 20000,
Давай еще индикатор загрузки добавим, он очень наглядный. Смотри пример, как я это сделал для создания пула (`isCreatePoolLoading`)

2023-05-13 15:16 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +        timeout: 20000,
but there are no buttons here... should the dialog be kept opened in the loading case?

2023-05-13 16:10 UTC, fedosov commented on app/components/dialogs/DialogIdentity.tsx
> +        timeout: 20000,
Да, ты прав, диалоговое окно должно оставаться открытым до окончания операции. В этом окне есть же кнопка? Вот ее можно сделать loading

2023-05-13 18:53 UTC, evgeniikozhanov commented on app/components/dialogs/DialogIdentity.tsx
> +        timeout: 20000,
done

2023-05-13 19:01 UTC, fedosov reviewed
Буду тестировать, спасибо!

2023-05-16 20:30 UTC, fedosov commented
Во время теста получил такую ошибку:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '1')
    at Account.client.tsx:109:46

<img width="702" alt="image" src="https://github.com/3Dpass/wallet/assets/556770/ae2d5cf4-27d9-419b-8929-4411acac7025">

Данные заполнял такие же как и всегда (описал выше), регистратора выбирал Caldera

2023-05-16 20:59 UTC, evgeniikozhanov commented
> Во время теста получил такую ошибку (завис на окне и вечная загрузка):
> 
> ```
> Uncaught (in promise) TypeError: Cannot read properties of undefined (reading '1')
>     at Account.client.tsx:109:46
> ```
> 
> <img alt="image" width="702" src="https://user-images.githubusercontent.com/556770/238765025-ae2d5cf4-27d9-419b-8929-4411acac7025.png">
> Данные заполнял такие же как и всегда (описал выше), регистратора выбирал Caldera

Ah, yes, I faced this one, but then I forgot about it. I added a condition to prevent using undefined in this clause.

2023-05-25 18:50 UTC, merged