Mining Pool: add setPoolMode calling
3Dpass/wallet pull request #25
Opened 2023-04-29 10:36 UTC by evgeniikozhanov

2023-04-29 15:22 UTC, fedosov requested changes

2023-04-29 15:22 UTC, fedosov commented on app/components/dialogs/DialogCreatePool.tsx
> +  const [poolMode, setPoolMode] = useState(false);
Давай назовем более понятно, типа `poolWithKYC`

2023-04-29 15:22 UTC, fedosov commented on app/components/dialogs/DialogCreatePool.tsx
> +            className="bp4-control absolute"
`Classes` для `bp4-control`

2023-04-29 22:10 UTC, evgeniikozhanov commented on app/components/dialogs/DialogCreatePool.tsx
> +  const [poolMode, setPoolMode] = useState(false);
this file was deleted :-(

2023-04-29 22:10 UTC, evgeniikozhanov commented on app/components/dialogs/DialogCreatePool.tsx
> +            className="bp4-control absolute"
this file was deleted :-(

2023-04-30 16:47 UTC, fedosov approved these changes

2023-04-30 16:47 UTC, fedosov commented on app/components/wallet/Account.client.tsx
> +                  {!poolAlreadyExist && <Button text="Create" onClick={handleCreatePoolClick} disabled={accountLocked} />}
У нас пока нет в кошельке отображение Identity, но когда будет нужно учесть, что создать будет без Identity нельзя. Т.е. надо будет при наведении показать что нужно Identity сначала получить

2023-04-30 16:47 UTC, merged